In [1]:
import os
import numpy as np
import cv2

In [2]:
os.listdir("../3xM/3xM_Dataset_0_1_1/cam_0")

['mask_0.png', 'raw_0.png']

In [3]:
img = cv2.imread("../3xM/3xM_Dataset_0_1_1/cam_0/mask_0.png")
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [ ]:
img = cv2.imread("../3xM/3xM_Dataset_0_1_1/cam_0/raw_0.png")
img

In [9]:
np.unique_counts(img)

UniqueCountsResult(values=array([ 0, 31, 61, 92], dtype=uint8), counts=array([6111959,  253034,  180162,   90365]))

In [13]:
os.listdir("../3xM-Test/OCID-dataset/ARID20/table/top/seq01/label")

['result_2018-08-21-11-10-42.png',
 'result_2018-08-21-11-20-37.png',
 'result_2018-08-21-11-12-38.png',
 'result_2018-08-21-11-11-22.png',
 'result_2018-08-21-11-07-29.png',
 'result_2018-08-21-11-23-11.png',
 'result_2018-08-21-10-59-55.png',
 'result_2018-08-21-11-19-19.png',
 'result_2018-08-21-11-16-05.png',
 'result_2018-08-21-11-15-28.png',
 'result_2018-08-21-11-22-46.png',
 'result_2018-08-21-11-11-59.png',
 'result_2018-08-21-11-08-54.png',
 'result_2018-08-21-11-04-41.png',
 'result_2018-08-21-11-04-15.png',
 'result_2018-08-21-11-23-54.png',
 'result_2018-08-21-11-10-08.png',
 'result_2018-08-21-11-21-24.png',
 'result_2018-08-21-11-17-03.png',
 'result_2018-08-21-11-18-28.png',
 'result_2018-08-21-11-07-57.png']

In [29]:
img = cv2.imread("../3xM-Test/OCID-dataset/ARID20/table/top/seq01/label/result_2018-08-21-10-59-55.png", cv2.IMREAD_UNCHANGED)
np.unique(img)

array([0, 1, 2], dtype=uint16)

In [24]:
img_new = img.astype(np.uint8)
np.unique(img_new)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20], dtype=uint8)

In [22]:
img

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint16)

In [25]:
img = cv2.imread("../3xM-Test/OCID-dataset/ARID20/table/top/seq01/rgb/result_2018-08-21-11-22-46.png", cv2.IMREAD_UNCHANGED)
img

array([[[140, 135, 110],
        [145, 139, 115],
        [133, 138, 110],
        ...,
        [124, 127, 104],
        [119, 126, 104],
        [118, 125, 103]],

       [[141, 134, 115],
        [145, 138, 118],
        [141, 137, 110],
        ...,
        [124, 118,  94],
        [101, 119,  93],
        [ 99, 117,  91]],

       [[131, 133, 113],
        [133, 136, 115],
        [133, 136, 115],
        ...,
        [114, 113,  88],
        [110, 111,  88],
        [107, 108,  85]],

       ...,

       [[ 80,  77,  52],
        [ 82,  79,  55],
        [ 89,  78,  57],
        ...,
        [ 87,  72,  47],
        [ 82,  73,  47],
        [ 82,  73,  47]],

       [[ 81,  78,  53],
        [ 83,  80,  56],
        [ 91,  81,  55],
        ...,
        [ 87,  72,  47],
        [ 87,  72,  47],
        [ 87,  72,  47]],

       [[ 92,  81,  60],
        [ 92,  81,  60],
        [ 95,  83,  58],
        ...,
        [ 88,  73,  48],
        [ 88,  73,  48],
        [ 88,  73,  48]]